//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace kellerkompanie_sync.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("kellerkompanie_sync.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Directory.
        /// </summary>
        public static string AddDirectory {
            get {
                return ResourceManager.GetString("AddDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Additional Parameters.
        /// </summary>
        public static string AdditionalParameters {
            get {
                return ResourceManager.GetString("AdditionalParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Addon Search Directories.
        /// </summary>
        public static string AddonSearchDirectories {
            get {
                return ResourceManager.GetString("AddonSearchDirectories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A list of directories on your computer in which the tool will look for addons (folders starting with @). You can also select folders that already contain addons, in which case the tool will try to discover existing addons before downloading..
        /// </summary>
        public static string AddonSearchDirectoriesExplanation {
            get {
                return ResourceManager.GetString("AddonSearchDirectoriesExplanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All addons present, but group is not subscribed.
        /// </summary>
        public static string AllModsDownloadedButNotSubscribed {
            get {
                return ResourceManager.GetString("AllModsDownloadedButNotSubscribed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All mods missing.
        /// </summary>
        public static string AllModsMissing {
            get {
                return ResourceManager.GetString("AllModsMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arma 3 executable location:.
        /// </summary>
        public static string ArmaExecutableLocation {
            get {
                return ResourceManager.GetString("ArmaExecutableLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue download.
        /// </summary>
        public static string Continue {
            get {
                return ResourceManager.GetString("Continue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to default world empty.
        /// </summary>
        public static string DefaultWorldEmpty {
            get {
                return ResourceManager.GetString("DefaultWorldEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading files....
        /// </summary>
        public static string DownloadingModsProgress {
            get {
                return ResourceManager.GetString("DownloadingModsProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download paused.
        /// </summary>
        public static string DownloadPausedProgress {
            get {
                return ResourceManager.GetString("DownloadPausedProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download Settings.
        /// </summary>
        public static string DownloadSettings {
            get {
                return ResourceManager.GetString("DownloadSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Everything up-to-date.
        /// </summary>
        public static string EverythingUpToDate {
            get {
                return ResourceManager.GetString("EverythingUpToDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Executable not found, check settings.
        /// </summary>
        public static string ExecutableNotFoundTooltip {
            get {
                return ResourceManager.GetString("ExecutableNotFoundTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forum.
        /// </summary>
        public static string Forum {
            get {
                return ResourceManager.GetString("Forum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to left.
        /// </summary>
        public static string Left {
            get {
                return ResourceManager.GetString("Left", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading Addons....
        /// </summary>
        public static string LoadingAddons {
            get {
                return ResourceManager.GetString("LoadingAddons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please first add a addon search directory under settings..
        /// </summary>
        public static string MissingAddonSearchDirectoryInfoMessage {
            get {
                return ResourceManager.GetString("MissingAddonSearchDirectoryInfoMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mods.
        /// </summary>
        public static string Mods {
            get {
                return ResourceManager.GetString("Mods", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Needs update.
        /// </summary>
        public static string NeedsUpdate {
            get {
                return ResourceManager.GetString("NeedsUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to News.
        /// </summary>
        public static string News {
            get {
                return ResourceManager.GetString("News", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to no logs.
        /// </summary>
        public static string NoLogs {
            get {
                return ResourceManager.GetString("NoLogs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to no pause.
        /// </summary>
        public static string NoPause {
            get {
                return ResourceManager.GetString("NoPause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to no splash screen.
        /// </summary>
        public static string NoSplashScreen {
            get {
                return ResourceManager.GetString("NoSplashScreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of simultaneous downloads:.
        /// </summary>
        public static string NumberOfSimultaneousDownloads {
            get {
                return ResourceManager.GetString("NumberOfSimultaneousDownloads", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        public static string Open {
            get {
                return ResourceManager.GetString("Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pause download.
        /// </summary>
        public static string Pause {
            get {
                return ResourceManager.GetString("Pause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play.
        /// </summary>
        public static string Play {
            get {
                return ResourceManager.GetString("Play", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comparing online version....
        /// </summary>
        public static string ProgressComparingOnlineVersion {
            get {
                return ResourceManager.GetString("ProgressComparingOnlineVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (downloading...).
        /// </summary>
        public static string ProgressDownloading {
            get {
                return ResourceManager.GetString("ProgressDownloading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (paused).
        /// </summary>
        public static string ProgressDownloadPaused {
            get {
                return ResourceManager.GetString("ProgressDownloadPaused", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indexing completed.
        /// </summary>
        public static string ProgressIndexingComplete {
            get {
                return ResourceManager.GetString("ProgressIndexingComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indexing your files....
        /// </summary>
        public static string ProgressIndexingFiles {
            get {
                return ResourceManager.GetString("ProgressIndexingFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (validating...).
        /// </summary>
        public static string ProgressValidating {
            get {
                return ResourceManager.GetString("ProgressValidating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ready.
        /// </summary>
        public static string Ready {
            get {
                return ResourceManager.GetString("Ready", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        public static string Remove {
            get {
                return ResourceManager.GetString("Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server.
        /// </summary>
        public static string Server {
            get {
                return ResourceManager.GetString("Server", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to show script errors.
        /// </summary>
        public static string ShowScriptErrors {
            get {
                return ResourceManager.GetString("ShowScriptErrors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some files already downloaded.
        /// </summary>
        public static string SomeModsAlreadyDownloaded {
            get {
                return ResourceManager.GetString("SomeModsAlreadyDownloaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Steam is not running, please start Steam first!.
        /// </summary>
        public static string SteamNotRunningInfoMessage {
            get {
                return ResourceManager.GetString("SteamNotRunningInfoMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subscribe.
        /// </summary>
        public static string Subscribe {
            get {
                return ResourceManager.GetString("Subscribe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teamspeak.
        /// </summary>
        public static string Teamspeak {
            get {
                return ResourceManager.GetString("Teamspeak", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teamspeak is running, please close Teamspeak before installing the TFAR plugin!.
        /// </summary>
        public static string TeamspeakNotRunningInfoMessage {
            get {
                return ResourceManager.GetString("TeamspeakNotRunningInfoMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TFAR.
        /// </summary>
        public static string TFAR {
            get {
                return ResourceManager.GetString("TFAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown.
        /// </summary>
        public static string Unknown {
            get {
                return ResourceManager.GetString("Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        public static string Update {
            get {
                return ResourceManager.GetString("Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open website.
        /// </summary>
        public static string Website {
            get {
                return ResourceManager.GetString("Website", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wiki.
        /// </summary>
        public static string Wiki {
            get {
                return ResourceManager.GetString("Wiki", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to window mode.
        /// </summary>
        public static string WindowMode {
            get {
                return ResourceManager.GetString("WindowMode", resourceCulture);
            }
        }
    }
}
